title: Vangelico's Fine Jewelry # name of the site
author: Vangelico # name of site's author
email: vangelico@example.com # email of site's author
url: https://vangelicos.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  System zapisywania transakcji złotem.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "vangelicos" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "Strona Główna" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
